Oro\Bundle\DPDBundle\Entity\DPDTransport:
    constraints:
        - Oro\Bundle\DPDBundle\Validator\Constraints\RemoveUsedShippingServiceConstraint: ~
    properties:
        cloudUserId:
            - NotBlank: ~
        cloudUserToken:
            - NotBlank: ~
        applicableShippingServices:
            - NotBlank:
                message: 'oro.dpd.transport.shipping_service.blank'
        unitOfWeight:
            - NotBlank: ~
            - Valid: ~
        rates:
            - Valid: ~
        ratesCsv:
            - Oro\Bundle\DPDBundle\Validator\Constraints\RatesCsvFileConstraint: ~
        labelSize:
            - NotBlank: ~
        labelStartPosition:
            - NotBlank: ~
        labels:
            - NotBlank: ~
            - Valid: ~

Oro\Bundle\DPDBundle\Entity\Rate:
    properties:
        transport:
            - NotBlank: ~
        shippingService:
            - NotBlank: ~
        country:
            - Valid: ~
        region:
            - Valid: ~
        priceValue:
            - NotBlank: ~
