oro_entity:
    entity_aliases:
        Oro\Bundle\DPDBundle\Entity\ShippingService:
            alias:        dpd_shipping_service
            plural_alias: dpd_shipping_services
        Oro\Bundle\DPDBundle\Entity\Rate:
            alias:        dpd_rate
            plural_alias: dpd_rates
